# Generated by Django 4.1.5 on 2023-03-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_category_remove_fooditem_category_fooditem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
    ]
