# Generated by Django 4.1.5 on 2023-03-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0004_remove_fooditem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
