# Generated by Django 4.1.5 on 2023-03-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
