# Generated by Django 4.1.5 on 2023-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0007_rename_category_name_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Item/images'),
        ),
    ]
