# Generated by Django 4.1.5 on 2023-03-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0009_alter_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Item/foodpicture'),
        ),
    ]
